# Generated by Django 6.0.5 on 2026-05-18 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress_message', models.CharField(blank=True, default='Waiting to process', max_length=255)),
                ('transcript', models.TextField(blank=True, default='')),
                ('toxic_spans', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
